### ISSUE TITLE
「ヘルプ」→「アップデートの確認」機能が動作しないのを修正してほしい。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon_macOS#11]
北島 健吾 🎸ハヤエモニックギタリスト
「ここからアプデ確認できるようにしたいでござる
まだわしの最新じゃないはずでござる」
https://twitter.com/kengo1228/status/995722697312161792

### 関連するissue
ryotayama/Hayaemon/issues/151

**Comment by kengo1228** [comment]
Mac版はApp Storeにない分更新を見落としがちなのでうまいこと誘導できるといいですねぇ。
