### ISSUE TITLE
(Mac版β) メニューバーの位置がMacのその他アプリとはちょっと違う

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_macOS#2]
◆使用しているOS：macOS版
◆使用しているバージョン：0.01β3
◆内容
Windowsに慣れてるので現状のほうが僕は好みではあるんですけども,

他のソフトと違って現在,メニューバー(上部のファイル,編集,表示とか)がアプリウィンドウ内に収められているのですが,Macの他のソフトは画面上部の時計とかリンゴマークとかのある場所に来ているので,純粋なMacユーザーさんが困惑するかも････?
◆関連issue
https://github.com/ryotayama/Hayaemon/issues/138

**Comment by DaisukeAtaraxiA** [comment]
デフォルトではmacOSネイティブスタイルである、デスクトップ上部のメニューバーにメニュー項目を表示。
ただし、メニューバーのHayaemon > Preferences...からメインメニューに表示するスタイルに変更できる。
