### ISSUE TITLE
保存機能で文字が正しく表示されない

### ISSUE THREAD

**Issue by kengo1228** [ryotayama/Hayaemon_macOS#31]
Version 0.01 β 4
半角英数字なら問題なかったが、全角で英数字や日本語入力をすると写真のような文字に変換されてしまう。
![2018-08-19 03 22 38](https://user-images.githubusercontent.com/39563982/44302217-2b641500-a35f-11e8-8ee2-6372f069cdc0.png)

**Comment by DaisukeAtaraxiA** [comment]
おそらくBassライブラリの国際化に関するバグです。
